### ISSUE TITLE
Use appsettings.json file

### ISSUE THREAD

**Issue by audunsolemdal** [equinor/ms-continuus#3]
Remove custom config logic, not a typical pattern in .NET

**Comment by sindre-nistad** [comment]
Note that `appsettings.json` is usually used in ASP.NET, and not in a standalone (i.e. non-ASP) .NET app.
We could add the ASP.NET package / make the project into one, @audunsolemdal?

**Comment by audunsolemdal** [comment]
Do what you think is best, don't have much experience with .NET outside ASP .NET apps.
