### ISSUE TITLE
Backups should be contained in folders

### ISSUE THREAD

**Issue by audunsolemdal** [equinor/ms-continuus#4]
Within a container - group tarballs from a backup within a folder. This makes it easier to navigate and delete the correct objects.

**Comment by sindre-nistad** [comment]
What format should the folder structure be?

**Comment by audunsolemdal** [comment]
I believe grouping tarballs by backup should be sufficient. 1 backup = 1 folder under the root level

Try to include date metadata into the folder name perhaps.
